// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxyF9Ns9HJPsjytfPQCRlhJiRsr4l0ugQ',
    appId: '1:991483925692:web:5a41a8d52025f863002cb9',
    messagingSenderId: '991483925692',
    projectId: 'whatsapp-messengr-386fc',
    authDomain: 'whatsapp-messengr-386fc.firebaseapp.com',
    storageBucket: 'whatsapp-messengr-386fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw71KMUlDJVRxKyY25l4uEBgPNvg8mI54',
    appId: '1:991483925692:android:9ecdd15a17707323002cb9',
    messagingSenderId: '991483925692',
    projectId: 'whatsapp-messengr-386fc',
    storageBucket: 'whatsapp-messengr-386fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeiNt7LB1A4Z27mkh1Q2JJd3dTk3OpYqU',
    appId: '1:991483925692:ios:73139ea524d20a99002cb9',
    messagingSenderId: '991483925692',
    projectId: 'whatsapp-messengr-386fc',
    storageBucket: 'whatsapp-messengr-386fc.appspot.com',
    iosBundleId: 'com.example.whatsappMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeiNt7LB1A4Z27mkh1Q2JJd3dTk3OpYqU',
    appId: '1:991483925692:ios:8ba321cf0ddbf46a002cb9',
    messagingSenderId: '991483925692',
    projectId: 'whatsapp-messengr-386fc',
    storageBucket: 'whatsapp-messengr-386fc.appspot.com',
    iosBundleId: 'com.example.whatsappMessenger.RunnerTests',
  );
}
